@echo off
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
start Msg.vbs
